spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb  # DB ??, ?? ??? ?? mydb ??? ??
    username: root                         # DB ????
    password: 1234                      # DB ????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # (create, update, validate, none ? ??)
    show-sql: true      # ???? SQL? ??


